   

from fpdf import FPDF
from typing import List, Dict

def sanitize_text(text: str) -> str:
           
    if not text:
        return ""
    
                                 
    replacements = {
        "\u2022": "-",                    
        "\u2013": "-",               
        "\u2014": "--",              
        "\u2018": "'",                         
        "\u2019": "'",                          
        "\u201c": '"',                         
        "\u201d": '"',                          
        "\u2122": "(TM)",              
        "\u00ae": "(R)",                
        "\u00a9": "(C)",               
    }
    
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    
                                                                            
    return text.encode("latin-1", "ignore").decode("latin-1")

class PDFReport(FPDF):
    def __init__(self, title="Contract Risk Assessment"):
        super().__init__()
        self.doc_title = sanitize_text(title)

    def header(self):
                     
        self.set_font("helvetica", "B", 16)
        self.set_text_color(26, 16, 64)            
        self.cell(0, 10, self.doc_title, border=False, align="C", ln=1)
        self.set_font("helvetica", "I", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, "Generated by Agentic Risk Analyzer", border=False, align="C", ln=1)
        self.ln(5)

    def footer(self):
                     
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", border=False, align="C")

def generate_pdf_report(analyzed_clauses: List[Dict], stats: Dict, meta: Dict) -> bytes:
           
    pdf = PDFReport(title="Contract Risk Assessment Report")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
                      
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, sanitize_text("Document Details"), ln=1)
    pdf.set_font("helvetica", "", 11)
    pdf.cell(0, 7, sanitize_text(f"File Name: {meta.get('name', 'Unknown')}"), ln=1)
    pdf.cell(0, 7, sanitize_text(f"File Type: {meta.get('file_type', 'Unknown')}"), ln=1)
    pdf.cell(0, 7, sanitize_text(f"File Size: {meta.get('size_kb', 0)} KB"), ln=1)
    pdf.ln(5)

                                
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, sanitize_text("Summary Statistics"), ln=1)
    pdf.set_font("helvetica", "", 11)
    
    pdf.cell(0, 7, sanitize_text(f"Total Clauses Analyzed: {stats['total']}"), ln=1)
    
    pdf.set_text_color(200, 0, 0)
    pdf.cell(0, 7, sanitize_text(f"Risky Clauses Found: {stats['risky_count']}"), ln=1)
    
    pdf.set_text_color(0, 150, 0)
    pdf.cell(0, 7, sanitize_text(f"Safe Clauses Found: {stats['safe_count']}"), ln=1)
    
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 7, sanitize_text(f"Overall Risk Level: {stats['risk_percentage']}%"), ln=1)
    pdf.ln(10)

                           
    risky_clauses = [c for c in analyzed_clauses if c["label"] == "Risky"]
    
    pdf.set_font("helvetica", "B", 14)
    if not risky_clauses:
        pdf.set_text_color(0, 150, 0)
        pdf.cell(0, 10, sanitize_text("No Risky Clauses Identified."), ln=1)
    else:
        pdf.set_text_color(200, 0, 0)
        pdf.cell(0, 10, sanitize_text("Risky Clauses Details"), ln=1)
        pdf.ln(2)

        for clause in risky_clauses:
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(0, 0, 0)
            
            conf_pct = int(clause["confidence"] * 100)
            pdf.cell(0, 8, sanitize_text(f"Clause #{clause['id']} - Risk Confidence: {conf_pct}%"), ln=1)
            
            pdf.set_font("helvetica", "I", 10)
            pdf.set_text_color(100, 100, 100)
            keywords = ", ".join(clause["matched_keywords"])
            categories = ", ".join(clause["categories"])
            pdf.cell(0, 6, sanitize_text(f"Matched Keywords: {keywords}"), ln=1)
            pdf.cell(0, 6, sanitize_text(f"Categories: {categories}"), ln=1)
            
            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(0, 6, sanitize_text(clause["text"]))
            pdf.ln(5)

                                                           
                                                                                         
    raw_output = pdf.output(dest='S')
    if isinstance(raw_output, str):
        return raw_output.encode('latin-1')
    return bytes(raw_output)
