"""
utils/export_handler.py
-----------------------
Handles the generation of PDF reports from the analyzed contract clauses using fpdf2.
"""

from fpdf import FPDF
from typing import List, Dict

class PDFReport(FPDF):
    def __init__(self, title="Contract Risk Assessment"):
        super().__init__()
        self.doc_title = title

    def header(self):
        # Header text
        self.set_font("helvetica", "B", 16)
        self.set_text_color(26, 16, 64) # Dark blue
        self.cell(0, 10, self.doc_title, border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("helvetica", "I", 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, "Generated by Agentic Risk Analyzer", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(5)

    def footer(self):
        # Footer text
        self.set_y(-15)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f"Page {self.page_no()}/{{nb}}", border=False, align="C", new_x="RIGHT")

def generate_pdf_report(analyzed_clauses: List[Dict], stats: Dict, meta: Dict) -> bytes:
    """
    Generates a professional PDF report containing the risk assessment.
    Returns the generated PDF as bytes.
    """
    pdf = PDFReport(title="Contract Risk Assessment Report")
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    
    # Metadata Section
    pdf.set_font("helvetica", "B", 14)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 10, "Document Details", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 11)
    pdf.cell(0, 7, f"File Name: {meta.get('name', 'Unknown')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"File Type: {meta.get('file_type', 'Unknown')}", new_x="LMARGIN", new_y="NEXT")
    pdf.cell(0, 7, f"File Size: {meta.get('size_kb', 0)} KB", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(5)

    # Summary Statistics Section
    pdf.set_font("helvetica", "B", 14)
    pdf.cell(0, 10, "Summary Statistics", new_x="LMARGIN", new_y="NEXT")
    pdf.set_font("helvetica", "", 11)
    
    pdf.cell(0, 7, f"Total Clauses Analyzed: {stats['total']}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_text_color(200, 0, 0)
    pdf.cell(0, 7, f"Risky Clauses Found: {stats['risky_count']}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_text_color(0, 150, 0)
    pdf.cell(0, 7, f"Safe Clauses Found: {stats['safe_count']}", new_x="LMARGIN", new_y="NEXT")
    
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 7, f"Overall Risk Level: {stats['risk_percentage']}%", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(10)

    # Risky Clauses Details
    risky_clauses = [c for c in analyzed_clauses if c["label"] == "Risky"]
    
    pdf.set_font("helvetica", "B", 14)
    if not risky_clauses:
        pdf.set_text_color(0, 150, 0)
        pdf.cell(0, 10, "No Risky Clauses Identified.", new_x="LMARGIN", new_y="NEXT")
    else:
        pdf.set_text_color(200, 0, 0)
        pdf.cell(0, 10, "Risky Clauses Details", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        for clause in risky_clauses:
            pdf.set_font("helvetica", "B", 12)
            pdf.set_text_color(0, 0, 0)
            
            conf_pct = int(clause["confidence"] * 100)
            pdf.cell(0, 8, f"Clause #{clause['id']} - Risk Confidence: {conf_pct}%", new_x="LMARGIN", new_y="NEXT")
            
            pdf.set_font("helvetica", "I", 10)
            pdf.set_text_color(100, 100, 100)
            keywords = ", ".join(clause["matched_keywords"])
            categories = ", ".join(clause["categories"])
            pdf.cell(0, 6, f"Matched Keywords: {keywords}", new_x="LMARGIN", new_y="NEXT")
            pdf.cell(0, 6, f"Categories: {categories}", new_x="LMARGIN", new_y="NEXT")
            
            pdf.set_font("helvetica", "", 10)
            pdf.set_text_color(50, 50, 50)
            pdf.multi_cell(0, 6, clause["text"], new_x="LMARGIN", new_y="NEXT")
            pdf.ln(5)

    return bytes(pdf.output())
